### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by shivambhatia5432**
Added definition of this project.

### CODE REVIEW

**Comment by git-anurag-hub** [comment]
Can you please write more about this. To give the basic idea this app deal similar to Instagram.
So you can add something like "It allow to follow peoples and post the images to keep connected". :)

**Comment by shivambhatia5432** [comment]
Hey, why did you close this request?

**Comment by git-anurag-hub** [comment]
Because the readme.md is already updated now.

**Comment by git-anurag-hub** [comment]
If you still want to update it. Update it with better version. :)

**Comment by shivambhatia5432** [comment]
Can you open this pull request so I can make changes here only instead of creating a new PR?

**Comment by shivambhatia5432** [comment]
It is showing conflicts in readme.md when I am commiting the changes.

**Comment by git-anurag-hub** [comment]
You should first fetch the code from this repo by usin git fetch command then make changes and committing them. :)

**Comment by shivambhatia5432** [comment]
Done

**Pull request merged**
