### PR TITLE
Add application description to README.md

### PR DESCRIPTION
**Pull request by AbderrahimSoubaiElidrissi**

### CODE REVIEW

**Review by git-anurag-hub — COMMENTED** [review]
Review your steps correctly. I mean you have to also install the dependencies for client also. Also add the tech it uses.

**Comment by AbderrahimSoubaiElidrissi** [comment]
@git-anurag-hub Done

**Comment by git-anurag-hub** [comment]
Spelling of install!

**Comment by AbderrahimSoubaiElidrissi** [comment]
Done too

**Pull request merged**
