### PR TITLE
feat: Create a image pond #8

### PR DESCRIPTION
**Pull request by salonigoyal2309**
resolves issue #8 
Image preview is created using https://github.com/pqina/filepond
Height is posts wrapper div is  converted to % so that when preview is generated it does not overflow the wrapper 
Tip: Always keep height/width of div in responsive units like % so that when view of your application changes your components will not get overflowed.
If you need any changes in the code feel free to mention them :)

### CODE REVIEW

**Comment by git-anurag-hub** [comment]
Have you tested the application by posting the image?

**Comment by salonigoyal2309** [comment]
@git-anurag-hub yes i tested it , it works on my device 
are you having any issues ?

**Comment by git-anurag-hub** [comment]
If you want you can do the same for editing avatar :))

**Comment by salonigoyal2309** [comment]
@git-anurag-hub sure i'll update that also

**Pull request merged**
